#R DATA TYPES

#DATA TYPE NUMERIC CONSISTE EM DECIMAIS CONHECIDOS COMO VALORES DE PONTO FLUTUANTE
2.2
a <- 2.2

#TAMBEM COMPORTA OS TIPOS INTEGER 
5
7

#CLASSE LÓGICA BOOLEANOS QUE SAO VERDADEIRO OU FALSO (EM R SÃO ESCRITO EM CAPSLOCK)
TRUE
T #ABREVIADO

FALSE
F #ABREVIADO

#STRINGS SÃO CARACTERES E VOCE PODE USAR ASPAS DUPLAS OU SIMPLES PARA CRIAR UMA CADEIA DE CARACTERES
'Olá Mundo'
b <- 'hello'
c <- "hello"

#CLASS RETORNA A CLASSE DA VARIAVEL ESPECIFICADA
class(a)
class(b)
class(T)
class(F)
