#FACTOR AND CATEGORICAL MATRICES

#ESTAREMOS UTILIZANDO UMA FUNCAO CHAMADA "FACTOR", USADA PARA CRIAR MATRIZES 
#CATEGORICAS ESTA FUNCAO E MUITO UTIL SE APLICADA A TECNICAS DE ANALISE DE DADOS
#E MACHINE LEARNING
 
#VAMOS PENSAR EM DADOS SIMPLES COMO ANIMAIS E DESENVOLVER UMA ESPECIE DE "ONG"
animal <- c('c','g','c','g','g')#SENDO C "CACHORROS" E G "GATOS"

#VAMOS CRIAR NUMEROS PARA FAZERMOS A IDENTIFICACAO DESTES ANIMAIS

id <- c(1,2,3,4,5)

#PRECISAMOS CONVERTER O VETOR DE ANIMAIS EN ALGORITIMO OU EQUACAO PARA ENETENDER 
#COM MAIS FACILIDADE, OU SEJA QUEREMOS VERIFICAR QUANTAS CATEGORIAS OU NIVEIS
# DE FATORES ESTAO REALMENTE EM NOSSO VETOR DE CARACTERES 
#E DESTA FOMRA USAMOS A FUNCAO "FACTOR"
factor(animal) #SEPARAMOS E NOS RETORNOU DOIS "NIVEIS" CONSTITUIDOS PELAS LETRAS "C" E "G"

#PRECISAMOS ATRIBUIR ESTE FATOR DE ANIMAL, E PARA ISSO VAMOS CRIAR UMA VARIAVEL

fact.ani <- factor(animal)

#ENTAO HAVERA DOIS TIPOS DISTINTOS DE VARIAVEIS CATEGORICAS ORDINAIS E NOMINAIS
#AS VARIAVEIS NOMINAIS NOS PERMITEM ENTRAR E DIGITA-LAS, PORTANTOS 
#AS CATEGORICAS NOMINAIS NAO POSSUEM ORDEM, ENTAO PODEMOS IMAGINAR QUE
#CAES E GATOS NAO POSSUEM ORDEM PARA ELES 
#ORDINAL JA POSSUEM ORDEM COMO ESPERADO VINDO DO NOME 
ord.cat <- c('gel','med','quente')#PODEMOS VER QUE SEGUIMOS UMA ORDEM 

#SE QUISERMOS REALMENTE ATRIBUIR UM PEDIDO A ESSAS VARIAVEIS PODEMOS FAZER ISSO
#USANDO A FUNCAO "FACTOR" UTILIZANDO UM AGUMENTO ORDENADO IGUAL A TRUE E PASSAR
#O ARGUMENTO DE "NIVEL"
#COMO POR EXEMPLO: DIGAMOS QUE TEMOS UMA TEMPERATURA VETORIAL E ELA SERA CHAMADA
#DE MEDIA.

temps <- c('gelado','medium','quente','gelado','quente','gelado','quente')
temps
#AGORA TEMOS TRES CATEGORIAS, AGORA VAMOS PASSAR ISSO PARA UMA VARIAVEL USANDO
#"FACTOR" VAMOS DIZER QUE A VERSAO FATORADA FUNCAO PASSA NO VETOR "TEMPS"

#NAO FIZEMOS ISSO NO VETOR DE CAES E GATOS
#POIS NAO HAVIA NENHUMA ORDEM DIFERENTE DO VETOR TEMPS QUE E ORDENADO EM 3 CATEGORIAS
#ORDERED FUNCAO UTILIZADA JUNTO DE "FACTOR" PARA AUXILIAR EM VETORES ORDINAIS
#"LEVELS ARGUMENT" ELE CARREGARA PARA O VETOR NA ORDEM QUE VOCE QUER E PRECISA 
#QUE SEJA PASSADA 
fact.temp <- factor(temps,ordered = T,levels = c('gelado','medium','quente')) 
fact.temp

#SUMARY E UMA FUNCAO DE RESUMO, PODEMOS CHAMAR UM RESUMO SOBRE ESTE OBJETO
summary(fact.temp)
#PODEMOS VER QUE ELE COLETOU INFORMACOES DE FORMA ORDENADA DE CADA TEMPERATURA
#E QUANTAS VEZES CADA UMA SE REPETE OU RELATAM SUA QUANTIDADE.


