#MATRIX SELECTION AND INDEXING
#VAMOS CRIAR UMA MATRIZ QUE FUNCIONA COMO UM VETOR SEQUENCIAL DE 1 A 50
mat <- matrix(1:50, byrow = T, nrow = 5)

#COMO DE COSTUME EM UA MATRIZ PODEMOS ESCOLHER A LINHA QUE QUEREMOS VERIFICAR
mat[1,]

#E COMO PODEMOS SELECIONAR A PRIMEIRA COLUNA? PODEMOS COLOCAR A PRIMEIRA COLUNA
# SEM CONTER QUALQUER NUMERAÇÃO COMO POR EXEMPLO

mat[,1]
#ELE PEGARÁ APENAS OS RESOLTADOS DA COLUNA 1 DO EIXO X

#PODEMOS SELECIONAR O NUMERO DE LINHAS DO EIXO X E FILTRAR TODOS OS VALORES PARA
#CADA LINHA DA SEGUINTE FORMA:
mat[1:3,]

#PODEMOS FILTRAR O RESULTADO DO EIXO Y E SELECIONAR OS VALORES DO EIXO X 
mat[1:2,1:3]

#PODEMOS SELECIONAS AS ULTIMAS COLUNAS E MOSTRA-LAS 
mat[,9:10]

#PODEMOS FILTRAR PARA SELECIONAR PARTES ESPECIFICAS DA NOSSA MATRIZ 
mat[2:3,5:6]
